package main

import "fmt"

func addORMModels() bool {
	// GORM does not do this automatically
	dbOrm.Exec("UPDATE pg_opclass SET opcdefault = true WHERE opcname='gin_trgm_ops'")

	// ORM MIGRATION!
	// DROP TRIGGERS

	dbOrm.Exec("DROP TRIGGER IF EXISTS set_account_id ON public.account")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_account_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_accounting_movement_id ON public.accounting_movement")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_accounting_movement_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_accounting_movement_detail_id ON public.accounting_movement_detail")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_accounting_movement_detail_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_address_id ON public.address")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_address_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_api_key_id ON public.api_key")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_api_key_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_carrier_id ON public.carrier")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_carrier_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_charges_id ON public.charges")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_charges_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_collection_operation_id ON public.collection_operation")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_collection_operation_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_color_id ON public.color")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_color_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_complex_manufacturing_order_id ON public.complex_manufacturing_order")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_complex_manufacturing_order_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_complex_manufacturing_order_manufacturing_order_id ON public.complex_manufacturing_order_manufacturing_order")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_complex_manufacturing_order_manufacturing_order_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_config_id ON public.config")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_config_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_connection_filter_id ON public.connection_filter")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_connection_filter_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_connection_filter_id ON public.connection_filter")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_connection_filter_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_country_id ON public.country")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_country_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_currency_id ON public.currency")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_currency_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_custom_fields_id ON public.custom_fields")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_custom_fields_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_customer_id ON public.customer")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_customer_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_document_id ON public.document")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_document_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_document_container_id ON public.document_container")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_document_container_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_email_log_id ON public.email_log")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_email_log_id")
	dbOrm.Exec(`DROP TRIGGER IF EXISTS set_group_id ON public."group"`)
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_group_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_incoterm_id ON public.incoterm")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_incoterm_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_inventory_id ON public.inventory")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_inventory_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_language_id ON public.language")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_language_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_login_tokens_id ON public.login_tokens")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_login_tokens_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_logs_id ON public.logs")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_logs_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_manufacturing_order_id ON public.manufacturing_order")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_manufacturing_order_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_manufacturing_order_type_id ON public.manufacturing_order_type")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_manufacturing_order_type_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_manufacturing_order_type_components_id ON public.manufacturing_order_type_components")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_manufacturing_order_type_components_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_packages_id ON public.packages")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_packages_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_packaging_id ON public.packaging")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_packaging_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_pallets_id ON public.pallets")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_pallets_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_payment_method_id ON public.payment_method")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_payment_method_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_payment_transaction_id ON public.payment_transaction")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_payment_transaction_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_payments_id ON public.payments")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_payments_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_pos_terminals_id ON public.pos_terminals")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_pos_terminals_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_product_id ON public.product")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_product_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_product_account_id ON public.product_account")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_product_account_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_product_family_id ON public.product_family")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_product_family_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_product_image_id ON public.product_image")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_product_image_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_purchase_delivery_note_id ON public.purchase_delivery_note")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_purchase_delivery_note_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_purchase_invoice_id ON public.purchase_invoice")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_purchase_invoice_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_purchase_invoice_details_id ON public.purchase_invoice_details")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_purchase_invoice_details_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_purchase_order_id ON public.purchase_order")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_purchase_order_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_purchase_order_detail_id ON public.purchase_order_detail")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_purchase_order_detail_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_sales_delivery_note_id ON public.sales_delivery_note")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_sales_delivery_note_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_sales_invoice_id ON public.sales_invoice")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_sales_invoice_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_sales_invoice_detail_id ON public.sales_invoice_detail")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_sales_invoice_detail_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_sales_order_id ON public.sales_order")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_sales_order_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_sales_order_detail_id ON public.sales_order_detail")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_sales_order_detail_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_sales_order_detail_digital_product_data_id ON public.sales_order_detail_digital_product_data")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_sales_order_detail_digital_product_data_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_sales_order_discount_id ON public.sales_order_discount")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_sales_order_discount_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_shipping_id ON public.shipping")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_shipping_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_shipping_status_history_id ON public.shipping_status_history")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_shipping_status_history_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_shipping_tag_id ON public.shipping_tag")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_shipping_tag_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_state_id ON public.state")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_state_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_suppliers_id ON public.suppliers")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_suppliers_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_transactional_log_id ON public.transactional_log")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_transactional_log_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_transfer_between_warehouses_id ON public.transfer_between_warehouses")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_transfer_between_warehouses_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_transfer_between_warehouses_detail_id ON public.transfer_between_warehouses_detail")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_transfer_between_warehouses_detail_id")
	dbOrm.Exec(`DROP TRIGGER IF EXISTS set_user_id ON public."user"`)
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_user_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_warehouse_movement_id ON public.warehouse_movement")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_warehouse_movement_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_webhook_logs_id ON public.webhook_logs")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_webhook_logs_id")
	dbOrm.Exec("DROP TRIGGER IF EXISTS set_webhook_settings_id ON public.webhook_settings")
	dbOrm.Exec("DROP FUNCTION IF EXISTS set_webhook_settings_id")

	// DROP FUNCIONS
	// OTHERS
	dbOrm.Exec("DROP TABLE IF EXISTS product_translation")
	dbOrm.Exec("ALTER TABLE public.connection_filter DROP COLUMN IF EXISTS time_start")
	dbOrm.Exec("ALTER TABLE public.connection_filter DROP COLUMN IF EXISTS time_end")
	dbOrm.Exec("ALTER TABLE public.connection_filter ADD COLUMN time_start timestamp(0) with time zone")
	dbOrm.Exec("ALTER TABLE public.connection_filter ADD COLUMN time_end timestamp(0) with time zone")
	// SWITCH EVERY REAL NUMBER TO NUMBERIC(12,6) TO DOUBLE PRECISION
	dbOrm.Exec("ALTER TABLE public.currency ALTER COLUMN exchange TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.config ALTER COLUMN default_vat_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.config ALTER COLUMN pallet_weight TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.config ALTER COLUMN pallet_width TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.config ALTER COLUMN pallet_height TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.config ALTER COLUMN pallet_depth TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.account ALTER COLUMN credit TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.account ALTER COLUMN debit TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.account ALTER COLUMN balance TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.carrier ALTER COLUMN max_weight TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.carrier ALTER COLUMN max_width TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.carrier ALTER COLUMN max_height TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.carrier ALTER COLUMN max_depth TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.packages ALTER COLUMN weight TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.packages ALTER COLUMN width TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.packages ALTER COLUMN height TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.packages ALTER COLUMN depth TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.product ALTER COLUMN weight TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.product ALTER COLUMN width TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.product ALTER COLUMN height TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.product ALTER COLUMN depth TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.product ALTER COLUMN vat_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.product ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.product ALTER COLUMN purchase_price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.product ALTER COLUMN cost_price TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.config_accounts_vat ALTER COLUMN vat_percent TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.accounting_movement ALTER COLUMN amount_debit TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.accounting_movement ALTER COLUMN amount_credit TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.accounting_movement_detail ALTER COLUMN credit TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.accounting_movement_detail ALTER COLUMN debit TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.collection_operation ALTER COLUMN total TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.collection_operation ALTER COLUMN paid TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.collection_operation ALTER COLUMN pending TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.payment_transaction ALTER COLUMN total TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.payment_transaction ALTER COLUMN paid TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.payment_transaction ALTER COLUMN pending TYPE numeric(14, 6) ")

	dbOrm.Exec("ALTER TABLE public.charges ALTER COLUMN amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.payments ALTER COLUMN credit TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.custom_fields ALTER COLUMN value_number TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.sales_order ALTER COLUMN currency_change TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order ALTER COLUMN total_products TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order ALTER COLUMN discount_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order ALTER COLUMN fix_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order ALTER COLUMN shipping_price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order ALTER COLUMN shipping_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order ALTER COLUMN total_with_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order ALTER COLUMN vat_amount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.sales_order_detail ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail ALTER COLUMN vat_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.sales_invoice ALTER COLUMN currency_change TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice ALTER COLUMN total_products TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice ALTER COLUMN discount_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice ALTER COLUMN fix_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice ALTER COLUMN shipping_price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice ALTER COLUMN shipping_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice ALTER COLUMN total_with_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice ALTER COLUMN vat_amount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.sales_invoice_detail ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice_detail ALTER COLUMN vat_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_invoice_detail ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.sales_delivery_note ALTER COLUMN currency_change TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note ALTER COLUMN total_products TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note ALTER COLUMN discount_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note ALTER COLUMN fix_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note ALTER COLUMN shipping_price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note ALTER COLUMN shipping_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note ALTER COLUMN total_with_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note ALTER COLUMN vat_amount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.purchase_order ALTER COLUMN currency_change TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order ALTER COLUMN total_products TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order ALTER COLUMN discount_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order ALTER COLUMN fix_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order ALTER COLUMN shipping_price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order ALTER COLUMN shipping_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order ALTER COLUMN total_with_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order ALTER COLUMN total_vat TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.purchase_order_detail ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order_detail ALTER COLUMN vat_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_order_detail ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.purchase_invoice ALTER COLUMN currency_change TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice ALTER COLUMN total_products TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice ALTER COLUMN discount_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice ALTER COLUMN fix_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice ALTER COLUMN shipping_price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice ALTER COLUMN shipping_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice ALTER COLUMN total_with_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice ALTER COLUMN vat_amount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.purchase_invoice_details ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice_details ALTER COLUMN vat_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice_details ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.warehouse_movement ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement ALTER COLUMN vat_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.shipping ALTER COLUMN weight TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.pallets ALTER COLUMN weight TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.pallets ALTER COLUMN width TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.pallets ALTER COLUMN height TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.pallets ALTER COLUMN depth TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.packaging ALTER COLUMN weight TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.sales_order_discount ALTER COLUMN value_tax_included TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sales_order_discount ALTER COLUMN value_tax_excluded TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note ALTER COLUMN currency_change TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note ALTER COLUMN total_products TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note ALTER COLUMN discount_percent TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note ALTER COLUMN fix_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note ALTER COLUMN shipping_price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note ALTER COLUMN shipping_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note ALTER COLUMN total_with_discount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note ALTER COLUMN total_vat TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note ALTER COLUMN total_amount TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.ps_currency ALTER COLUMN conversion_rate TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.ps_order ALTER COLUMN total_discounts_tax_excl TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.ps_order ALTER COLUMN total_shipping_tax_excl TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.ps_order_detail ALTER COLUMN product_price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.ps_product ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.ps_product_combination ALTER COLUMN price TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.sy_draft_order_line_item ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sy_draft_orders ALTER COLUMN total_tax TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sy_order_line_item ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sy_orders ALTER COLUMN total_shipping_price_set_amount TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sy_orders ALTER COLUMN total_tax TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.sy_variants ALTER COLUMN price TYPE numeric(14, 6)")

	dbOrm.Exec("ALTER TABLE public.wc_order_details ALTER COLUMN price TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.wc_order_details ALTER COLUMN total_tax TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.wc_orders ALTER COLUMN discount_tax TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.wc_orders ALTER COLUMN shipping_total TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.wc_orders ALTER COLUMN shipping_tax TYPE numeric(14, 6)")
	dbOrm.Exec("ALTER TABLE public.wc_orders ALTER COLUMN total_tax TYPE numeric(14, 6)")

	// DROP MANUAL (NON-ORM) FOREIGN KEY CONSTRAINTS

	dbOrm.Exec("ALTER TABLE public.account DROP CONSTRAINT IF EXISTS account_enterprise")
	dbOrm.Exec("ALTER TABLE public.account DROP CONSTRAINT IF EXISTS account_journal")
	dbOrm.Exec("ALTER TABLE public.accounting_movement DROP CONSTRAINT IF EXISTS accounting_movement_billing_serie")
	dbOrm.Exec("ALTER TABLE public.accounting_movement DROP CONSTRAINT IF EXISTS accounting_movement_enterprise")
	dbOrm.Exec("ALTER TABLE public.accounting_movement_detail DROP CONSTRAINT IF EXISTS accounting_movement_detail_payment_method")
	dbOrm.Exec("ALTER TABLE public.accounting_movement_detail DROP CONSTRAINT IF EXISTS accounting_movement_detail_account")
	dbOrm.Exec("ALTER TABLE public.accounting_movement_detail DROP CONSTRAINT IF EXISTS accounting_movement_detail_enterprise")
	dbOrm.Exec("ALTER TABLE public.accounting_movement_detail DROP CONSTRAINT IF EXISTS accounting_movement_detail_journal")
	dbOrm.Exec("ALTER TABLE public.accounting_movement_detail DROP CONSTRAINT IF EXISTS accounting_movement_detail_movement")
	dbOrm.Exec("ALTER TABLE public.address DROP CONSTRAINT IF EXISTS address_country")
	dbOrm.Exec("ALTER TABLE public.address DROP CONSTRAINT IF EXISTS address_customer")
	dbOrm.Exec("ALTER TABLE public.address DROP CONSTRAINT IF EXISTS address_enterprise")
	dbOrm.Exec("ALTER TABLE public.address DROP CONSTRAINT IF EXISTS address_state")
	dbOrm.Exec("ALTER TABLE public.api_key DROP CONSTRAINT IF EXISTS api_key_enterprise")
	dbOrm.Exec("ALTER TABLE public.api_key DROP CONSTRAINT IF EXISTS api_key_user")
	dbOrm.Exec("ALTER TABLE public.api_key DROP CONSTRAINT IF EXISTS api_key_user_created")
	dbOrm.Exec("ALTER TABLE public.billing_series DROP CONSTRAINT IF EXISTS billing_series_enterprise")
	dbOrm.Exec("ALTER TABLE public.carrier DROP CONSTRAINT IF EXISTS carrier_enterprise")
	dbOrm.Exec("ALTER TABLE public.charges DROP CONSTRAINT IF EXISTS charges_account")
	dbOrm.Exec("ALTER TABLE public.charges DROP CONSTRAINT IF EXISTS charges_accounting_movement")
	dbOrm.Exec("ALTER TABLE public.charges DROP CONSTRAINT IF EXISTS charges_accounting_movement_detail_credit")
	dbOrm.Exec("ALTER TABLE public.charges DROP CONSTRAINT IF EXISTS charges_accounting_movement_detail_debit")
	dbOrm.Exec("ALTER TABLE public.charges DROP CONSTRAINT IF EXISTS charges_collection_operation")
	dbOrm.Exec("ALTER TABLE public.charges DROP CONSTRAINT IF EXISTS charges_enterprise")
	dbOrm.Exec("ALTER TABLE public.collection_operation DROP CONSTRAINT IF EXISTS collection_operation_account")
	dbOrm.Exec("ALTER TABLE public.collection_operation DROP CONSTRAINT IF EXISTS collection_operation_accounting_movement")
	dbOrm.Exec("ALTER TABLE public.collection_operation DROP CONSTRAINT IF EXISTS collection_operation_accounting_movement_detail")
	dbOrm.Exec("ALTER TABLE public.collection_operation DROP CONSTRAINT IF EXISTS collection_operation_bank")
	dbOrm.Exec("ALTER TABLE public.collection_operation DROP CONSTRAINT IF EXISTS collection_operation_enterprise")
	dbOrm.Exec("ALTER TABLE public.collection_operation DROP CONSTRAINT IF EXISTS collection_operation_payment_method")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_enterprise")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_type")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_user_manufactured")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_warehouse")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_complex_manufacturing_order")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_manufacturing_order")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_manufacturing_order_complex_manufac")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_manufacturing_order_enterprise")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_manufacturing_order_manufacturing_o")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_manufacturing_order_product")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_manufacturing_order_purchase_order_")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_manufacturing_order_sale_order_deta")
	dbOrm.Exec("ALTER TABLE public.complex_manufacturing_order_manufacturing_order DROP CONSTRAINT IF EXISTS complex_manufacturing_order_manufacturing_order_warehouse_movem")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_customer_journal")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_prestashop_export_serie")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_prestashop_interior_serie")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_prestashop_intracommunity_serie")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_purchase_account")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_purchase_journal")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_sales_account")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_sales_journal")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_shopify_default_payment_method")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_shopify_export_serie")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_shopify_interior_serie")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_shopify_intracommunity_serie")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_supplier_journal")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_warehouse")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_woocommerce_default_payment_method")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_woocommerce_export_serie")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_woocommerce_interior_serie")
	dbOrm.Exec("ALTER TABLE public.config DROP CONSTRAINT IF EXISTS config_woocommerce_intracommunity_serie")
	dbOrm.Exec("ALTER TABLE public.config_accounts_vat DROP CONSTRAINT IF EXISTS config_accounts_vat_account_purchase")
	dbOrm.Exec("ALTER TABLE public.config_accounts_vat DROP CONSTRAINT IF EXISTS config_accounts_vat_account_sales")
	dbOrm.Exec("ALTER TABLE public.config_accounts_vat DROP CONSTRAINT IF EXISTS config_accounts_vat_enterprise")
	dbOrm.Exec("ALTER TABLE public.connection_filter DROP CONSTRAINT IF EXISTS connection_filter_enterprise")
	dbOrm.Exec("ALTER TABLE public.connection_filter_user DROP CONSTRAINT IF EXISTS connection_filter_user_connection_filter")
	dbOrm.Exec("ALTER TABLE public.connection_filter_user DROP CONSTRAINT IF EXISTS connection_filter_user_user")
	dbOrm.Exec("ALTER TABLE public.connection_log DROP CONSTRAINT IF EXISTS connection_log_enterprise")
	dbOrm.Exec("ALTER TABLE public.connection_log DROP CONSTRAINT IF EXISTS connection_log_user")
	dbOrm.Exec("ALTER TABLE public.country DROP CONSTRAINT IF EXISTS country_currency")
	dbOrm.Exec("ALTER TABLE public.country DROP CONSTRAINT IF EXISTS country_enterprise")
	dbOrm.Exec("ALTER TABLE public.country DROP CONSTRAINT IF EXISTS country_language")
	dbOrm.Exec("ALTER TABLE public.currency DROP CONSTRAINT IF EXISTS currency_enterprise")
	dbOrm.Exec("ALTER TABLE public.custom_fields DROP CONSTRAINT IF EXISTS custom_fields_customer")
	dbOrm.Exec("ALTER TABLE public.custom_fields DROP CONSTRAINT IF EXISTS custom_fields_enterprise")
	dbOrm.Exec("ALTER TABLE public.custom_fields DROP CONSTRAINT IF EXISTS custom_fields_product")
	dbOrm.Exec("ALTER TABLE public.custom_fields DROP CONSTRAINT IF EXISTS custom_fields_supplier")
	dbOrm.Exec("ALTER TABLE public.custom_fields DROP CONSTRAINT IF EXISTS custom_fields_customer")
	dbOrm.Exec("ALTER TABLE public.custom_fields DROP CONSTRAINT IF EXISTS custom_fields_enterprise")
	dbOrm.Exec("ALTER TABLE public.custom_fields DROP CONSTRAINT IF EXISTS custom_fields_product")
	dbOrm.Exec("ALTER TABLE public.custom_fields DROP CONSTRAINT IF EXISTS custom_fields_supplier")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_account")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_billing_series")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_country")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_enterprise")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_language")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_main_address")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_main_billing_address")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_main_shipping_address")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_payment_method")
	dbOrm.Exec("ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_state")
	dbOrm.Exec("ALTER TABLE public.document DROP CONSTRAINT IF EXISTS document_container")
	dbOrm.Exec("ALTER TABLE public.document DROP CONSTRAINT IF EXISTS document_enterprise")
	dbOrm.Exec("ALTER TABLE public.document DROP CONSTRAINT IF EXISTS document_purchase_delivery_note")
	dbOrm.Exec("ALTER TABLE public.document DROP CONSTRAINT IF EXISTS document_purchase_invoice")
	dbOrm.Exec("ALTER TABLE public.document DROP CONSTRAINT IF EXISTS document_purchase_order")
	dbOrm.Exec("ALTER TABLE public.document DROP CONSTRAINT IF EXISTS document_sales_delivery_note")
	dbOrm.Exec("ALTER TABLE public.document DROP CONSTRAINT IF EXISTS document_sales_invoice")
	dbOrm.Exec("ALTER TABLE public.document DROP CONSTRAINT IF EXISTS document_sales_order")
	dbOrm.Exec("ALTER TABLE public.document DROP CONSTRAINT IF EXISTS document_shipping")
	dbOrm.Exec("ALTER TABLE public.document_container DROP CONSTRAINT IF EXISTS document_container_enterprise")
	dbOrm.Exec("ALTER TABLE public.email_log DROP CONSTRAINT IF EXISTS email_log_enterprise")
	dbOrm.Exec("ALTER TABLE public.enterprise_logo DROP CONSTRAINT IF EXISTS enterprise_logo_enterprise")
	dbOrm.Exec(`ALTER TABLE public."group" DROP CONSTRAINT IF EXISTS group_enterprise`)
	dbOrm.Exec("ALTER TABLE public.incoterm DROP CONSTRAINT IF EXISTS incoterm_enterprise")
	dbOrm.Exec("ALTER TABLE public.inventory DROP CONSTRAINT IF EXISTS inventory_enterprise")
	dbOrm.Exec("ALTER TABLE public.inventory DROP CONSTRAINT IF EXISTS inventory_warehouse")
	dbOrm.Exec("ALTER TABLE public.inventory_products DROP CONSTRAINT IF EXISTS inventory_products_enterprise")
	dbOrm.Exec("ALTER TABLE public.inventory_products DROP CONSTRAINT IF EXISTS inventory_products_inventory")
	dbOrm.Exec("ALTER TABLE public.inventory_products DROP CONSTRAINT IF EXISTS inventory_products_product")
	dbOrm.Exec("ALTER TABLE public.inventory_products DROP CONSTRAINT IF EXISTS inventory_products_warehouse_movement")
	dbOrm.Exec("ALTER TABLE public.journal DROP CONSTRAINT IF EXISTS journal_enterprise")
	dbOrm.Exec("ALTER TABLE public.language DROP CONSTRAINT IF EXISTS language_enterprise")
	dbOrm.Exec("ALTER TABLE public.login_tokens DROP CONSTRAINT IF EXISTS login_tokens_user")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order DROP CONSTRAINT IF EXISTS manufacturing_order_enterprise")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order DROP CONSTRAINT IF EXISTS manufacturing_order_order")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order DROP CONSTRAINT IF EXISTS manufacturing_order_order_detail")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order DROP CONSTRAINT IF EXISTS manufacturing_order_product")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order DROP CONSTRAINT IF EXISTS manufacturing_order_type")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order DROP CONSTRAINT IF EXISTS manufacturing_order_user_created")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order DROP CONSTRAINT IF EXISTS manufacturing_order_user_manufactured")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order DROP CONSTRAINT IF EXISTS manufacturing_order_warehouse")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order DROP CONSTRAINT IF EXISTS manufacturing_order_warehouse_movement")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order_type DROP CONSTRAINT IF EXISTS manufacturing_order_type_enterprise")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order_type_components DROP CONSTRAINT IF EXISTS manufacturing_order_type_components_enterprise")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order_type_components DROP CONSTRAINT IF EXISTS manufacturing_order_type_components_manufacturing_order_type")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order_type_components DROP CONSTRAINT IF EXISTS manufacturing_order_type_components_manufacturing_order_type2")
	dbOrm.Exec("ALTER TABLE public.manufacturing_order_type_components DROP CONSTRAINT IF EXISTS manufacturing_order_type_components_product")
	dbOrm.Exec("ALTER TABLE public.packages DROP CONSTRAINT IF EXISTS packages_enterprise")
	dbOrm.Exec("ALTER TABLE public.packages DROP CONSTRAINT IF EXISTS packages_product")
	dbOrm.Exec("ALTER TABLE public.packaging DROP CONSTRAINT IF EXISTS packaging_enterprise")
	dbOrm.Exec("ALTER TABLE public.packaging DROP CONSTRAINT IF EXISTS packaging_package")
	dbOrm.Exec("ALTER TABLE public.packaging DROP CONSTRAINT IF EXISTS packaging_pallet")
	dbOrm.Exec("ALTER TABLE public.packaging DROP CONSTRAINT IF EXISTS packaging_sales_order")
	dbOrm.Exec("ALTER TABLE public.packaging DROP CONSTRAINT IF EXISTS packaging_shipping")
	dbOrm.Exec("ALTER TABLE public.pallets DROP CONSTRAINT IF EXISTS pallets_sales_order")
	dbOrm.Exec("ALTER TABLE public.pallets DROP CONSTRAINT IF EXISTS pallets_enterprise")
	dbOrm.Exec("ALTER TABLE public.payment_method DROP CONSTRAINT IF EXISTS payment_method_enterprise")
	dbOrm.Exec("ALTER TABLE public.payment_transaction DROP CONSTRAINT IF EXISTS payment_transaction_account")
	dbOrm.Exec("ALTER TABLE public.payment_transaction DROP CONSTRAINT IF EXISTS payment_transaction_accounting_movement")
	dbOrm.Exec("ALTER TABLE public.payment_transaction DROP CONSTRAINT IF EXISTS payment_transaction_accounting_movement_detail")
	dbOrm.Exec("ALTER TABLE public.payment_transaction DROP CONSTRAINT IF EXISTS payment_transaction_bank")
	dbOrm.Exec("ALTER TABLE public.payment_transaction DROP CONSTRAINT IF EXISTS payment_transaction_enterprise")
	dbOrm.Exec("ALTER TABLE public.payment_transaction DROP CONSTRAINT IF EXISTS payment_transaction_payment_method")
	dbOrm.Exec("ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_account")
	dbOrm.Exec("ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_accounting_movement")
	dbOrm.Exec("ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_accounting_movement_detail_credit")
	dbOrm.Exec("ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_accounting_movement_detail_debit")
	dbOrm.Exec("ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_enterprise")
	dbOrm.Exec("ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_payment_transaction")
	dbOrm.Exec("ALTER TABLE public.permission_dictionary DROP CONSTRAINT IF EXISTS permission_dictionary_enterprise")
	dbOrm.Exec("ALTER TABLE public.permission_dictionary_group DROP CONSTRAINT IF EXISTS permission_dictionary_group_enterprise")
	dbOrm.Exec("ALTER TABLE public.permission_dictionary_group DROP CONSTRAINT IF EXISTS permission_dictionary_group_group")
	dbOrm.Exec("ALTER TABLE public.permission_dictionary_group DROP CONSTRAINT IF EXISTS permission_dictionary_group_permission")
	dbOrm.Exec("ALTER TABLE public.pos_terminals DROP CONSTRAINT IF EXISTS pos_terminals_enterprise")
	dbOrm.Exec("ALTER TABLE public.pos_terminals DROP CONSTRAINT IF EXISTS pos_terminals_orders_billing_series")
	dbOrm.Exec("ALTER TABLE public.pos_terminals DROP CONSTRAINT IF EXISTS pos_terminals_orders_currency")
	dbOrm.Exec("ALTER TABLE public.pos_terminals DROP CONSTRAINT IF EXISTS pos_terminals_orders_customer")
	dbOrm.Exec("ALTER TABLE public.pos_terminals DROP CONSTRAINT IF EXISTS pos_terminals_orders_delivery_address")
	dbOrm.Exec("ALTER TABLE public.pos_terminals DROP CONSTRAINT IF EXISTS pos_terminals_orders_invoice_address")
	dbOrm.Exec("ALTER TABLE public.pos_terminals DROP CONSTRAINT IF EXISTS pos_terminals_orders_payment_method")
	dbOrm.Exec("ALTER TABLE public.pos_terminals DROP CONSTRAINT IF EXISTS pos_terminals_orders_warehouse")
	dbOrm.Exec("ALTER TABLE public.product DROP CONSTRAINT IF EXISTS product_color")
	dbOrm.Exec("ALTER TABLE public.product DROP CONSTRAINT IF EXISTS product_enterprise")
	dbOrm.Exec("ALTER TABLE public.product DROP CONSTRAINT IF EXISTS product_manufacturing_order_type")
	dbOrm.Exec("ALTER TABLE public.product DROP CONSTRAINT IF EXISTS product_product_family")
	dbOrm.Exec("ALTER TABLE public.product DROP CONSTRAINT IF EXISTS product_supplier")
	dbOrm.Exec("ALTER TABLE public.product_account DROP CONSTRAINT IF EXISTS poduct_account_account")
	dbOrm.Exec("ALTER TABLE public.product_account DROP CONSTRAINT IF EXISTS poduct_account_enterprise")
	dbOrm.Exec("ALTER TABLE public.product_family DROP CONSTRAINT IF EXISTS product_family_enterprise")
	dbOrm.Exec("ALTER TABLE public.product_image DROP CONSTRAINT IF EXISTS product_image_product")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note DROP CONSTRAINT IF EXISTS purchase_delivery_note_billing_series")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note DROP CONSTRAINT IF EXISTS purchase_delivery_note_currency")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note DROP CONSTRAINT IF EXISTS purchase_delivery_note_enterprise")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note DROP CONSTRAINT IF EXISTS purchase_delivery_note_payment_method")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note DROP CONSTRAINT IF EXISTS purchase_delivery_note_shipping_address")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note DROP CONSTRAINT IF EXISTS purchase_delivery_note_supplier")
	dbOrm.Exec("ALTER TABLE public.purchase_delivery_note DROP CONSTRAINT IF EXISTS purchase_delivery_note_warehouse")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice DROP CONSTRAINT IF EXISTS purchase_invoice_accounting_movement")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice DROP CONSTRAINT IF EXISTS purchase_invoice_amended_purchase_invoice")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice DROP CONSTRAINT IF EXISTS purchase_invoice_billing_address")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice DROP CONSTRAINT IF EXISTS purchase_invoice_billing_series")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice DROP CONSTRAINT IF EXISTS purchase_invoice_currency")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice DROP CONSTRAINT IF EXISTS purchase_invoice_payment_method")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice DROP CONSTRAINT IF EXISTS purchase_invoice_supplier")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice_details DROP CONSTRAINT IF EXISTS purchase_invoice_details_enterprise")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice_details DROP CONSTRAINT IF EXISTS purchase_invoice_details_invoice")
	dbOrm.Exec("ALTER TABLE public.purchase_invoice_details DROP CONSTRAINT IF EXISTS purchase_invoice_details_product")
	dbOrm.Exec("ALTER TABLE public.purchase_order DROP CONSTRAINT IF EXISTS purchase_order_billing_address")
	dbOrm.Exec("ALTER TABLE public.purchase_order DROP CONSTRAINT IF EXISTS purchase_order_billing_series")
	dbOrm.Exec("ALTER TABLE public.purchase_order DROP CONSTRAINT IF EXISTS purchase_order_currency")
	dbOrm.Exec("ALTER TABLE public.purchase_order DROP CONSTRAINT IF EXISTS purchase_order_enterprise")
	dbOrm.Exec("ALTER TABLE public.purchase_order DROP CONSTRAINT IF EXISTS purchase_order_payment_method")
	dbOrm.Exec("ALTER TABLE public.purchase_order DROP CONSTRAINT IF EXISTS purchase_order_shipping_address")
	dbOrm.Exec("ALTER TABLE public.purchase_order DROP CONSTRAINT IF EXISTS purchase_order_supplier")
	dbOrm.Exec("ALTER TABLE public.purchase_order DROP CONSTRAINT IF EXISTS purchase_order_warehouse")
	dbOrm.Exec("ALTER TABLE public.purchase_order_detail DROP CONSTRAINT IF EXISTS purchase_order_detail_enterprise")
	dbOrm.Exec("ALTER TABLE public.purchase_order_detail DROP CONSTRAINT IF EXISTS purchase_order_detail_order")
	dbOrm.Exec("ALTER TABLE public.purchase_order_detail DROP CONSTRAINT IF EXISTS purchase_order_detail_product")
	dbOrm.Exec("ALTER TABLE public.report_template DROP CONSTRAINT IF EXISTS report_template_enterprise")
	dbOrm.Exec("ALTER TABLE public.report_template_translation DROP CONSTRAINT IF EXISTS report_template_translation_enterprise")
	dbOrm.Exec("ALTER TABLE public.report_template_translation DROP CONSTRAINT IF EXISTS report_template_translation_language")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note DROP CONSTRAINT IF EXISTS sales_delivery_note_billing_series")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note DROP CONSTRAINT IF EXISTS sales_delivery_note_currency")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note DROP CONSTRAINT IF EXISTS sales_delivery_note_customer")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note DROP CONSTRAINT IF EXISTS sales_delivery_note_enterprise")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note DROP CONSTRAINT IF EXISTS sales_delivery_note_payment_method")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note DROP CONSTRAINT IF EXISTS sales_delivery_note_shipping_address")
	dbOrm.Exec("ALTER TABLE public.sales_delivery_note DROP CONSTRAINT IF EXISTS sales_delivery_note_warehouse")
	dbOrm.Exec("ALTER TABLE public.sales_invoice DROP CONSTRAINT IF EXISTS sales_invoice_accounting_movement")
	dbOrm.Exec("ALTER TABLE public.sales_invoice DROP CONSTRAINT IF EXISTS sales_invoice_amended_sales_invoice")
	dbOrm.Exec("ALTER TABLE public.sales_invoice DROP CONSTRAINT IF EXISTS sales_invoice_billing_address")
	dbOrm.Exec("ALTER TABLE public.sales_invoice DROP CONSTRAINT IF EXISTS sales_invoice_billing_series")
	dbOrm.Exec("ALTER TABLE public.sales_invoice DROP CONSTRAINT IF EXISTS sales_invoice_currency")
	dbOrm.Exec("ALTER TABLE public.sales_invoice DROP CONSTRAINT IF EXISTS sales_invoice_customer")
	dbOrm.Exec("ALTER TABLE public.sales_invoice DROP CONSTRAINT IF EXISTS sales_invoice_enterprise")
	dbOrm.Exec("ALTER TABLE public.sales_invoice DROP CONSTRAINT IF EXISTS sales_invoice_payment_method")
	dbOrm.Exec("ALTER TABLE public.sales_invoice_detail DROP CONSTRAINT IF EXISTS sales_invoice_detail_enterprise")
	dbOrm.Exec("ALTER TABLE public.sales_invoice_detail DROP CONSTRAINT IF EXISTS sales_invoice_detail_invoice")
	dbOrm.Exec("ALTER TABLE public.sales_invoice_detail DROP CONSTRAINT IF EXISTS sales_invoice_detail_order_detail")
	dbOrm.Exec("ALTER TABLE public.sales_invoice_detail DROP CONSTRAINT IF EXISTS sales_invoice_detail_product")
	dbOrm.Exec("ALTER TABLE public.sales_order DROP CONSTRAINT IF EXISTS sales_order_billing_address")
	dbOrm.Exec("ALTER TABLE public.sales_order DROP CONSTRAINT IF EXISTS sales_order_billing_series")
	dbOrm.Exec("ALTER TABLE public.sales_order DROP CONSTRAINT IF EXISTS sales_order_carrier")
	dbOrm.Exec("ALTER TABLE public.sales_order DROP CONSTRAINT IF EXISTS sales_order_currency")
	dbOrm.Exec("ALTER TABLE public.sales_order DROP CONSTRAINT IF EXISTS sales_order_customer")
	dbOrm.Exec("ALTER TABLE public.sales_order DROP CONSTRAINT IF EXISTS sales_order_enterprise")
	dbOrm.Exec("ALTER TABLE public.sales_order DROP CONSTRAINT IF EXISTS sales_order_payment_method")
	dbOrm.Exec("ALTER TABLE public.sales_order DROP CONSTRAINT IF EXISTS sales_order_shipping_address")
	dbOrm.Exec("ALTER TABLE public.sales_order DROP CONSTRAINT IF EXISTS sales_order_warehouse")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail DROP CONSTRAINT IF EXISTS sales_order_detail_enterprise")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail DROP CONSTRAINT IF EXISTS sales_order_detail_order")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail DROP CONSTRAINT IF EXISTS sales_order_detail_product")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail DROP CONSTRAINT IF EXISTS sales_order_detail_purchase_order_detail")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail_digital_product_data DROP CONSTRAINT IF EXISTS sales_order_detail_digital_product_data_sales_order_detail")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail_packaged DROP CONSTRAINT IF EXISTS sales_order_detail_enterprise")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail_packaged DROP CONSTRAINT IF EXISTS sales_order_detail_packaged_order_detail")
	dbOrm.Exec("ALTER TABLE public.sales_order_detail_packaged DROP CONSTRAINT IF EXISTS sales_order_detail_packaged_packaging")
	dbOrm.Exec("ALTER TABLE public.sales_order_discount DROP CONSTRAINT IF EXISTS sales_order_discount_enterprise")
	dbOrm.Exec("ALTER TABLE public.sales_order_discount DROP CONSTRAINT IF EXISTS sales_order_discount_order")
	dbOrm.Exec("ALTER TABLE public.sales_order_discount DROP CONSTRAINT IF EXISTS sales_order_discount_sales_invoice_detail")
	dbOrm.Exec("ALTER TABLE public.shipping DROP CONSTRAINT IF EXISTS shipping_carrier")
	dbOrm.Exec("ALTER TABLE public.shipping DROP CONSTRAINT IF EXISTS shipping_delivery_address")
	dbOrm.Exec("ALTER TABLE public.shipping DROP CONSTRAINT IF EXISTS shipping_delivery_note")
	dbOrm.Exec("ALTER TABLE public.shipping DROP CONSTRAINT IF EXISTS shipping_enterprise")
	dbOrm.Exec("ALTER TABLE public.shipping DROP CONSTRAINT IF EXISTS shipping_incoterm")
	dbOrm.Exec("ALTER TABLE public.shipping DROP CONSTRAINT IF EXISTS shipping_order")
	dbOrm.Exec("ALTER TABLE public.shipping_status_history DROP CONSTRAINT IF EXISTS shipping_status_history_shipping")
	dbOrm.Exec("ALTER TABLE public.shipping_tag DROP CONSTRAINT IF EXISTS shipping_tag_enterprise")
	dbOrm.Exec("ALTER TABLE public.shipping_tag DROP CONSTRAINT IF EXISTS shipping_tag_shipping")
	dbOrm.Exec("ALTER TABLE public.state DROP CONSTRAINT IF EXISTS state_country")
	dbOrm.Exec("ALTER TABLE public.state DROP CONSTRAINT IF EXISTS state_enterprise")
	dbOrm.Exec("ALTER TABLE public.stock DROP CONSTRAINT IF EXISTS stock_enterprise")
	dbOrm.Exec("ALTER TABLE public.stock DROP CONSTRAINT IF EXISTS stock_product")
	dbOrm.Exec("ALTER TABLE public.stock DROP CONSTRAINT IF EXISTS stock_warehouse")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_account")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_billing_series")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_country")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_enterprise")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_language")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_main_address")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_main_billing_address")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_main_shipping_address")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_payment_method")
	dbOrm.Exec("ALTER TABLE public.suppliers DROP CONSTRAINT IF EXISTS suppliers_state")
	dbOrm.Exec("ALTER TABLE public.transactional_log DROP CONSTRAINT IF EXISTS transactional_log_user")
	dbOrm.Exec("ALTER TABLE public.transfer_between_warehouses DROP CONSTRAINT IF EXISTS transfer_between_warehouses_enterprise")
	dbOrm.Exec("ALTER TABLE public.transfer_between_warehouses DROP CONSTRAINT IF EXISTS transfer_between_warehouses_warehouse_destination")
	dbOrm.Exec("ALTER TABLE public.transfer_between_warehouses DROP CONSTRAINT IF EXISTS transfer_between_warehouses_warehouse_origin")
	dbOrm.Exec("ALTER TABLE public.transfer_between_warehouses_detail DROP CONSTRAINT IF EXISTS transfer_between_warehouses_detail_enterprise")
	dbOrm.Exec("ALTER TABLE public.transfer_between_warehouses_detail DROP CONSTRAINT IF EXISTS transfer_between_warehouses_detail_product")
	dbOrm.Exec("ALTER TABLE public.transfer_between_warehouses_detail DROP CONSTRAINT IF EXISTS transfer_between_warehouses_detail_transfer_between_warehouses")
	dbOrm.Exec("ALTER TABLE public.transfer_between_warehouses_detail DROP CONSTRAINT IF EXISTS transfer_between_warehouses_detail_warehouse_movement_in")
	dbOrm.Exec("ALTER TABLE public.transfer_between_warehouses_detail DROP CONSTRAINT IF EXISTS transfer_between_warehouses_detail_warehouse_movement_out")
	dbOrm.Exec(`ALTER TABLE public."user" DROP CONSTRAINT IF EXISTS user_enterprise`)
	dbOrm.Exec("ALTER TABLE public.user_group DROP CONSTRAINT IF EXISTS user_group_group")
	dbOrm.Exec("ALTER TABLE public.user_group DROP CONSTRAINT IF EXISTS user_group_user")
	dbOrm.Exec("ALTER TABLE public.warehouse DROP CONSTRAINT IF EXISTS warehouse_enterprise")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement DROP CONSTRAINT IF EXISTS warehouse_movement_enterprise")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement DROP CONSTRAINT IF EXISTS warehouse_movement_product")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement DROP CONSTRAINT IF EXISTS warehouse_movement_purchase_delivery_note")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement DROP CONSTRAINT IF EXISTS warehouse_movement_purchase_order")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement DROP CONSTRAINT IF EXISTS warehouse_movement_purchase_order_detail")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement DROP CONSTRAINT IF EXISTS warehouse_movement_sales_delivery_note")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement DROP CONSTRAINT IF EXISTS warehouse_movement_sales_order")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement DROP CONSTRAINT IF EXISTS warehouse_movement_sales_order_detail")
	dbOrm.Exec("ALTER TABLE public.warehouse_movement DROP CONSTRAINT IF EXISTS warehouse_movement_warehouse")
	dbOrm.Exec("ALTER TABLE public.webhook_logs DROP CONSTRAINT IF EXISTS webhook_logs_enterprise")
	dbOrm.Exec("ALTER TABLE public.webhook_logs DROP CONSTRAINT IF EXISTS webhook_logs_webhook")
	dbOrm.Exec("ALTER TABLE public.webhook_queue DROP CONSTRAINT IF EXISTS webhook_queue_enterprise")
	dbOrm.Exec("ALTER TABLE public.webhook_queue DROP CONSTRAINT IF EXISTS webhook_queue_webhook")
	dbOrm.Exec("ALTER TABLE public.webhook_settings DROP CONSTRAINT IF EXISTS webhook_settings_enterprise")

	// MIGRATION!
	dbOrm.Exec("ALTER TABLE public.currency ALTER COLUMN exchange_date DROP DEFAULT")
	dbOrm.Exec("DROP INDEX IF EXISTS billing_series_id_enterprise")
	dbOrm.Exec("ALTER TABLE public.product_account DROP COLUMN IF EXISTS account_number")
	dbOrm.Exec("DELETE FROM color WHERE enterprise = 0")
	dbOrm.Exec("ALTER TABLE public.shipping_status_history DROP CONSTRAINT IF EXISTS shipping_status_history_pkey")
	dbOrm.Exec("ALTER TABLE public.shipping_status_history ADD PRIMARY KEY (id, shipping)")

	err := dbOrm.AutoMigrate(&Country{}, &Language{}, &Currency{}, &Warehouse{}, &Settings{}, &BillingSerie{}, &PaymentMethod{}, &Account{}, &Journal{},
		&User{}, &Group{}, &UserGroup{}, &PermissionDictionary{}, &PermissionDictionaryGroup{}, &DocumentContainer{}, &Document{}, &ProductFamily{}, &ProductAccount{},
		&Carrier{}, &State{}, &Color{}, &Packages{}, &Incoterm{}, &Product{}, &ConfigAccountsVat{}, &ManufacturingOrderType{}, &ManufacturingOrderTypeComponents{},
		&Supplier{}, &Address{}, &Customer{}, &AccountingMovement{}, &AccountingMovementDetail{}, &CollectionOperation{}, &PaymentTransaction{}, &Charges{}, &Payment{},
		&ApiKey{}, &ConnectionLog{}, &ConnectionFilter{}, &ConnectionFilterUser{}, &EmailLog{}, &CustomFields{}, &HSCode{}, &LoginToken{}, &POSTerminal{}, &WebHookSettings{},
		&WebHookLog{}, &WebHookRequest{}, &ReportTemplate{}, &ReportTemplateTranslation{}, &TransactionalLog{}, &SaleOrder{}, &SalesOrderDetail{}, &SalesInvoice{}, &SalesInvoiceDetail{},
		&SalesDeliveryNote{}, &PurchaseOrder{}, &PurchaseOrderDetail{}, &PurchaseInvoice{}, &PurchaseInvoiceDetail{}, &PurchaseDeliveryNote{}, &WarehouseMovement{}, &Stock{}, &Shipping{},
		&TransferBetweenWarehouses{}, &TransferBetweenWarehousesDetail{}, &Inventory{}, &InventoryProducts{}, &ManufacturingOrder{}, &ComplexManufacturingOrder{},
		&ComplexManufacturingOrderManufacturingOrder{}, &EnterpriseLogo{}, &Pallet{}, &Packaging{}, &SalesOrderDetailPackaged{}, &SalesOrderDetailDigitalProductData{}, &SalesOrderDiscount{},
		&ShippingStatusHistory{}, &ShippingTag{}, &ProductImage{}, &PwdBlacklist{}, &PwdSHA1Blacklist{}, &PSAddress{}, &PSCarrier{}, &PSCountry{}, &PSCurrency{}, &PSCustomer{}, &PSLanguage{},
		&PSOrder{}, &PSOrderDetail{}, &PSProduct{}, &PSProductCombination{}, &PSProductOptionValue{}, &PSState{}, &PSZone{}, &SYAddress{}, &SYCustomer{}, &SYDraftOrderLineItem{}, &SYDraftOrder{},
		&SYOrderLineItem{}, &SYOrder{}, &SYProduct{}, &SYVariant{}, &WCCustomer{}, &WCOrderDetail{}, &WCOrder{}, &WCProductVariation{}, &WCProduct{}) // 109
	if err != nil {
		fmt.Println(err)
		log("AutoMigrate", err.Error())
		return false
	}
	return true
}
